/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  // tutorialSidebar: [
  //   {
  //     type: 'category',
  //     label: 'Tutorial',
  //     items: ['hello'],
  //   },
  // ],
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Welcome',
      collapsed: false,
      items: [
        'Introduction'
      ],
    },
    {
      type: 'category',
      label: 'Technology  & Design',
      collapsed: false,
      items: [
        'Technology/know-ahead',
        'Technology/Technology',
        'Technology/About-Security',
      ],
    },
    {
      type: 'category',
      label: 'Network Information',
      collapsed: false,
      items: [
        'networks/mainnet_networks',
        'networks/mainnet_addresses',
        'networks/testnet_networks',
        'networks/testnet_addresses'
      ],
    },
    {
      type: 'category',
      label: 'Wallet & User Fund Streamline',
      collapsed: false,
      items: [
        'streamline/deposit',
        'streamline/withdraw',
        'streamline/wallet'
      ],
    },
    {
      type: 'category',
      label: 'Integration Architecture',
      collapsed: false,
      items: [
        'Integration Architecture/Derivatives',
        'Integration Architecture/spot',
        'Integration Architecture/zkjump'
      ],
    },
    {
      type: 'doc',
      id: 'Audits',
      label: 'Audits'
    },
    {
      type: 'doc',
      id: 'Token Economy',
      label: 'Tokenomics'
    },
    {
      type: 'doc',
      id: 'Smart Contract',
      label: 'Smart Contract'
    },
    {
      type: 'doc',
      id: 'community',
      label: 'Community'
    }
  ]
};
